# Generated by Django 4.2.13 on 2024-05-23 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='chai/images')),
                ('offer', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Milk Chai'), ('BL', 'Black Chai'), ('GR', 'Green Chai'), ('WH', 'White Chai'), ('OT', 'Other Chai')], default='OT', max_length=2)),
            ],
        ),
    ]
